name: CI
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 1.20.2
    - name: Test
      working-directory: ./finance
      run: go test -v ./... -coverprofile=./c.out && go tool cover -html=./c.out -o ./coverage.html
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: tukangremot/gows
